// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vphrjtiralycgupnyjyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwaHJqdGlyYWx5Y2d1cG55anl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTQ3NTQsImV4cCI6MjA2MDE5MDc1NH0.rn_qgzs9ZNtqYM0ieB4MRVuy25kb-_nZSJGSYF0ExLI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);